* Statistical Analysis and Data Exploration
Boston Housing dataset statistics (in $1000's):

Total number of houses: 506
Total number of features: 13
Minimum house price: 5.0
Maximum house price: 50.0
Mean house price: 22.533
Median house price: 21.2
Standard deviation of house price: 9.188
** Question 1: 
   - Of the features available for each data point, choose three that you feel are significant and give a brief description for each of what they measure.
** Question 2:
   - *Using your client's feature set `CLIENT_FEATURES`, which values correspond with the features you've chosen above?*  
* Evaluating Model Performance
** Question 3
   - *Why do we split the data into training and testing subsets for our model?*
** Question 4
   - *Which performance metric below did you find was most appropriate for predicting housing prices and analyzing the total error. Why?*
** Question 5
   - *What is the grid search algorithm and when is it applicable?*
** Question 6
   - *What is cross-validation, and how is it performed on a model? Why would cross-validation be helpful when using grid search?*
* Analyzing Model Performance
** Question 7
   - *Choose one of the learning curve graphs that are created above. What is the max depth for the chosen model? As the size of the training set increases, what happens to the training error? What happens to the testing error?*
** Question 8
   - *Look at the learning curve graphs for the model with a max depth of 1 and a max depth of 10. When the model is using the full training set, does it suffer from high bias or high variance when the max depth is 1? What about when the max depth is 10?*
** Question 9
   - *From the model complexity graph above, describe the training and testing errors as the max depth increases. Based on your interpretation of the graph, which max depth results in a model that best generalizes the dataset? Why?*

* Model Prediction
** Question 10
   - *Using grid search on the entire dataset, what is the optimal `max_depth` parameter for your model? How does this result compare to your intial intuition?*  
** Question 11
   - *With your parameter-tuned model, what is the best selling price for your client's home? How does this selling price compare to the basic statistics you calculated on the dataset?*  
** Question 12
   - *In a few sentences, discuss whether you would use this model or not to predict the selling price of future clients' homes in the Greater Boston area.*
